config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"

  resources :users

  resources :games, only: [:new, :index]

  resources :matches, only: [:create, :show]

  get "users/new" => "users#new", as: "sign_up"
  get "session/new" => "session#new", as: "log_in"

  get "/auth/:provider/callback" => "session#create_from_omniauth"

  post "session/new" => "session#create", as: "logging_in"
  delete "session/destroy" => "session#destroy", as: "log_out"

  post "/matches/:id/finished" => "matches#finished"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/authentication.rb
class Authentication < ApplicationRecord
	belongs_to :user

	def self.create_with_omniauth(omniauth_hash)
		auth = Authentication.new(provider: omniauth_hash["provider"], uid: omniauth_hash["uid"], token: omniauth_hash["credentials"]["token"])
	end

	def update_token(omniauth_hash)
		self.token = omniauth_hash["credentials"]["token"]
		self.save
	end
end

app/models/match.rb
class Match < ApplicationRecord

	# Scopes
	scope :not_full, -> { where("player_1 IS NOT NULL AND player_2 IS NULL") }

	# Status
	enum status: { ongoing: 0, finished: 1 }

	def find_creator(id)
		User.find(id)
	end
end

app/models/user.rb
class User < ApplicationRecord
	# user verification
	has_secure_password

	enum role: {user: 0, admin: 1, king: 2}

	# associations
	has_many :authentications, dependent: :destroy
	# validations
	validates :email, presence: true, uniqueness: true, format: { with: /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i, message: "Please Input A Valid Email Peasant"}
	validates :username, presence: true, uniqueness: true, length: { minimum: 5, message: "Your name is too short peasant"}
	validates :password, length: {minimum: 5}, presence: true, unless: "password.nil?"
	validates :password_confirmation, length: {minimum: 5}, presence: true, unless: "password.nil?"


	def self.create_with_auth_and_hash(authentication, omniauth_hash)
		password = SecureRandom.urlsafe_base64
		user = User.create!(username: omniauth_hash["extra"]["raw_info"]["name"] , email: omniauth_hash["extra"]["raw_info"]["email"], password: password, password_confirmation: password)
		user.authentications << (authentication)
		return user
	end

	def fb_token
			x = self.authentications.where(provider: :facebook).first
			return x.token unless x.nil?
	end

	private

	def self.authenticate(email, password)
		user = User.find_by(email: email)
  	if user && user.authenticate(password)
  		return user
  	else
  		nil
  	end
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/authentications_controller.rb
class AuthenticationsController < ApplicationController
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
	before_action :display, only: [:index]

	def index
	end

	def new
			@match = Match.new
	end

	private

	def display
		@matches = Match.not_full
	end

end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController

	before_action :find_match, only: [:show, :finished]
	before_action :find_player_1, only: [:finished]

	def create
		@category = params[:match][:category].capitalize
		response = Unirest.get "https://od-api.oxforddictionaries.com:443/api/v1/wordlist/en/domains%3D#{@category}?limit=3&offset=#{rand(1..50)}", headers: { "Accept" => "application/json", "app_id" => "d2092c51", "app_key" => "35fe0d68b185289c6bcd1f7050773e2a"}
		if response == nil
			flash[:notice] = "Type in another category"
		end
		@word = response.body["results"].sample["word"].gsub(/\s+/, "")
		@match = Match.new(category: @category, word: @word, player_1: session[:user_id])
		if @match.save
			redirect_to @match
		else
			redirect_to "/game/new"
		end
	end

	def show
		# decide player
		if User.find(@match.player_1) == User.find(session[:user_id])
			@player_1 = User.find(session[:user_id])
		elsif Match.find_creator(User.find(session[:user_id])) != User.find(session[:user_id]) && @match.player_2 == nil
			@player_2 = User.find(session[:user_id])
		elsif @match.player_1 != nil && @match.player_2 != nil
			redirect_to new_game_path
		end
		# lives of players
		@p1lives = @match.p1lives
		gon.watch.p1lives = @match.p1lives
		# array of correct words
		@word = @match.word.upcase.chars
		gon.word = @match.word.upcase.chars
		gon.puzzle = make_slots(@word)
		# delete btm
		@puzzle = make_slots(@word).join(" ")
		#delete top
		@alphabets = params["Alphabets"] unless params["Alphabets"].nil?
		if @word.index(@alphabets) == nil && @alphabets != nil
			@match.update(p1lives: (@match.p1lives - 1) )
		end
		respond_to do |format|
			format.js
			format.html
		end
	end

	def finished
		if params[:result] == "dead"
			if @player_1 == User.find(session[:user_id])
				@player_1.update(losses: @player_1.losses + 1)
				@match.update(status: 1)
				redirect_to @player_1
			end
		elsif params[:result] == "solved"
			if @player_1 == User.find(session[:user_id])
				@player_1.update(wins: @player_1.losses + 1)
				@match.update(status: 1)
				redirect_to @player_1
			end
		end
	end

	private

	def make_slots(word)
		array = []
		word.length.times do |x|
			x = "_"
			array << x
		end
		return array
	end

	def guess(word, alphabet)
		letter = [alphabet]
		number = word - letter
		number.length
	end

	def find_match
		@match = Match.find(params[:id])
	end

	def find_player_1
		@player_1 = User.find(params[:player1])
	end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
	def new
	end

	def create
		user = User.authenticate(params[:session][:email], params[:session][:password])
		if user && User.find_by_email(params[:session][:email])
			session[:user_id] = user.id
			redirect_to games_path
		else
			flash[:error] = "Login Failed"
			render "new"
		end
	end

	def create_from_omniauth
		omniauth_hash = request.env["omniauth.auth"]
		authentication = Authentication.find_by_provider_and_uid(omniauth_hash["provider"], omniauth_hash["uid"]) || Authentication.create_with_omniauth(omniauth_hash)

		if authentication.user
			user = authentication.user
			authentication.update_token(omniauth_hash)
		else
			user = User.create_with_auth_and_hash(authentication, omniauth_hash)
		end
		session[:user_id] = user.id
		redirect_to games_path
	end

	def destroy
		session[:user_id] = nil
		redirect_to root_path
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_action :find_user, only: [ :show, :edit, :update, :destroy ]


	def index
		@users = User.all
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			flash[:notice] = "You have successfuly joined the fun."
			redirect_to users_path(@user)
		else
			flash[:error] = "You have not successfuly joined the fun. Try again."
			render "new"
		end
	end

	def show
	end

	def edit
	end

	def update
		if @user.update(user_params)
			flash[:notice] = "Update succesful"
			redirect_to @user
		else
			flash[:error] = "Failed to update records"
			render "edit"
		end
	end

	def destroy
		@user.destroy
		redirect_to users_path
	end

	private

	def user_params
		params.require(:user).permit(:username, :email, :password, :password_confirmation)
	end

	def find_user
		@user = User.find(params[:id])
	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authentications_helper.rb
module AuthenticationsHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper

	def current_user
		if session[:user_id]
			@current_user ||= User.find(session[:user_id])
		end
	end

	def login?
		!current_user.nil?
	end


	def authorized?
		if current_user.role == "user"
			false
		else
			true
		end
	end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/games/index.html.erb
<% if login? %>
<div class="row">
	<div class="col-md-8 col-md-offset-2 col-xs-8 col-xs-offset-2">
		<h1 class="text-center">
			Currently Available Games
		</h1>
	</div>
</div>
<div id="available-matches-container">
	<div class="row">
		<% if @matches.count == 0 %>
			<div class="col-md-8 col-md-offset-2 col-xs-8 col-xs-offset-2">
					<h3 class="text-center"> No Ongoing Matches!</h3>
					<h3 class="text-center"> Create One Now</h3>
			</div>
			<div class="row">
				<div class="col-md-8 col-md-offset-2 col-xs-8 col-xs-offset-2 text-center">
					<%= link_to "Start A New Game", new_game_path, class: "btn btn-primary" %>
				</div>
			</div>
		<% else %>
				<ol class="col-md-8 col-md-offset-2 col-xs-8 col-xs-offset-2">
					<% @matches.each do |match| %>
						<% if match.find_creator(match.player_1) != current_user %>
							<li class="text-center"><%= link_to "Unoccupied Match", match_path(match), class: "btn btn-primary" %> </li>
						<% else %>
								<div class="col-md-8 col-md-offset-2 col-xs-8 col-xs-offset-2">
									<h3 class="text-center"> No Ongoing Matches By Others!</h3>
								</div>
						<% end %>
					<% end %>
				</ol>
		<% end %>
	</div>
</div>
<% else %>
	<div class="row">
		<div class="col-md-8 col-md-offset-2 col-xs-8 col-xs-2">
			Please Login
		</div>
	</div>
<% end %>

app/views/games/new.html.erb
<div class="row">
	<div class="col-md-8 col-xs-offset-2 col-xs-8 col-xs-offset-2">
		<h1 class="text-center">
		Type In Desired Category
		</h1>
	</div>
</div>
<div class="row">
	<div class="col-md-8 col-md-offset-2 col-xs-8 col-xs-offset-2 text-center">
		<%= form_for @match do |f| %>
			<div class="form-group">
				<%= f.text_field :category %>
				<%= f.submit "Select" %>
			</div>
		<% end %>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wholives</title>
    <%= csrf_meta_tags %>
    <%= Gon::Base.render_data %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
  <%= include_gon(:watch => true, :init => true) %>
  	<!-- navbar -->
  	<nav class="navbar navbar-default">
  		<div class="container-fluid">
	  		<div class="navbar-header">
	  			<a class="navbar-brand" href="/">WhoLives</a>
	  		</div>
	  		<ul class="nav navbar-nav">
		  		<li class="active"><a href="/">Home</a></li>
		  		<% if !login? %>
		  		<li><%= link_to "Login", log_in_path %></li>
		  		<% else %>
		  		<li><%= link_to "Profile", user_path(current_user)%></li>
          <li><%= link_to "All Games", games_path %></li>
          <li><%= link_to "New Game", new_game_path %></li>
		  		<li><%= link_to "Sign Out", log_out_path, method: :delete %></li>
		  		<% end %>
	  		</ul>
	  	</div>
  	</nav>
    <!-- content -->
    <div class="container-fluid">
      <%= yield %>
    </div>
  </body>
</html>

app/views/matches/new.html.erb
<p>
	Chosen category is <%= @category %>
</p>

app/views/matches/show.html.erb
<h1>Fight</h1>

<p><%= @match.category %></p>

<div class="container-fluid">
	<div class="row">
		<div class="col-md-8 col-md-offset-2" id="hangman-container">
			<div id="player1-lives">
				<% if @p1lives <= 0 %>
					<h2>You Are Dead</h2>
				<% else %>
					<h2><%= @p1lives %> lives left.</h2>
				<% end %>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-8 col-md-offset-2 col-xs-8 col-xs-offset-2" id ="puzzle-container">
		</div>
	</div>
	<br>
	<div class="row">
		<div class="col-md-8 col-md-offset-2" id="form-container">
				<%= form_tag("/matches/#{@match.id}", method: :get, remote: true, id: "guess-container") do %>
				<%= select_tag "Alphabets", options_for_select(("A".. "Z").to_a) %>
				<%= submit_tag "Guess" %>
				<% end %>
		</div>
	</div>
</div>
<div id="test">
</div>
<input type="hidden" data-id="<%= current_user.id%>" >

app/views/matches/show.js.erb
counter = 0
solved_counter = 0

$.each(gon.word, function(index, value){
	if (gon.word[index] === "<%= j @alphabets %>" ) {
		counter = counter - 1
	} else {
		counter = counter + 1
	}
})

gon.watch('p1lives', function(data){
	if (data <= 0 ) {
		$("#player1-lives").html("<h2 id='text'>You Are dead</h2>")
		$("#form-container").hide()
		$.ajax({
		url: '/matches/' + "<%=  @match.id %>" + "/finished",
		type: 'post',
		dataType: 'json',
		data: {result: 'dead', player1: <%= @player_1.id %>}
	})
	} else {
		$("#player1-lives").html("<h2 id='text'>" + data + " lives left.</h2>")
	}
})

if (counter != gon.word.length ) {
	$.each(gon.word, function(index, value) {
		if (gon.word[index] === "<%= j @alphabets %>") {
			$("#container" + index).html("<%= j @alphabets %>")
			for (i = 0; i < gon.word.length; i++ ) {
				 if( $(('#container' + i)).html() != "_ " ) {
				 	solved_counter = solved_counter + 1
				 }
			}
			if (solved_counter == gon.word.length) {
				$.ajax({
					url: '/matches/' + "<%=  @match.id %>" + "/finished",
					type: 'post',
					dataType: 'json',
					data: {result: 'solved', player1: <%= @player_1.id %>}
				})
			}
		}
	})
}

app/views/session/_form.html.erb
<%= form_for :session do |f| %>

<div class="form-group">
	<%= f.label :email, "Email" %>
	<%= f.email_field :email, class: "form-control" %>
</div>

<div class="form-group">
	<%= f.label :password, "Password" %>
	<%= f.password_field :password, class: "form-control" %>
</div>

<%= f.submit "Log In", class: "btn btn-danger" %>

<% end %>

app/views/session/new.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col-md-8 col-md-offset-2 col-xs-8 col-xs-offset-2">
			<h1 class="text-center">
				Come To Accept Your Fate?
			</h1>
		</div>
	</div>
	<div class="row">
		<div class="col-md-8 col-md-offset-2 col-xs-8 col-xs-offset-2">
			<%= render "form" %>
		</div>
	</div>
</div>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
	<div class="form-group">
		<%= f.label :username %>
		<%= f.text_field :username, class: "form-control"%>
	</div>

	<div class="form-group">
		<%= f.label :email %>
		<%= f.email_field :email, class: "form-control" %>
	</div>

	<div class="form-group">
		<%= f.label :password%>
		<%= f.password_field :password, class: "form-control" %>
	</div>

	<div class="form-group">
		<%= f.label :password_confirmation %>
		<%= f.password_field :password_confirmation, class: "form-control" %>
	</div>

	<%=  f.submit "#{@title}", class: "btn btn-danger" %>
<% end %>

app/views/users/edit.html.erb
<% @title = "Edit Profile" %>
<div class="container-fluid">
	<div class="row">
		<div class="col-md-8 col-md-offset-2 col-xs-8 col-xs-offset-2">
			<h1 class="text-center">
				Edit Your Records
			</h1>
		</div>
	</div>
	<div class="row">
		<div class="col-md-8 col-md-offset-2 col-xs-8 col-xs-offset-2">
			<%= render "form" %>
		</div>
	</div>
</div>

app/views/users/new.html.erb
<% @title =  "Sign Up" %>
<div class="container-fluid">
	<div class="row">
		<div class="col-md-8 col-md-offset-2 col-xs-8 col-xs-offset-2">
			<h1 class="text-center">
				Join The Fun
			</h1>
		</div>
	</div>
	<div class="row">
		<div class="col-md-8 col-md-offset-2 col-xs-8 col-xs-offset-2">
			<%= render "form" %>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col-md-8 col-md-offset-2 col-xs-8 col-xs-offset-2">
			<h1>
				Your Records
			</h1>
		</div>
	</div>
	<div class="row">
		<div class="col-md-8 col-offset-2 col-xs-8 col-xs-offset-2">
			<h2 class="text-center">
				Username
			</h2>
		</div>
	</div>
	<div class="row">
		<div class="col-md-8 col-offset-2 col-xs-8 col-xs-offset-2">
			<h4 class="text-center">
				<%= @user.username %>
			</h4>
		</div>
	</div>
	<div class="row">
		<div class="col-md-8 col-offset-2 col-xs-8 col-xs-offset-2">
			<h2 class="text-center">
				Email
			</h2>
		</div>
	</div>
	<div class="row">
		<div class="col-md-8 col-offset-2 col-xs-8 col-xs-offset-2">
			<h4 class="text-center">
				<%= @user.email %>
			</h4>
		</div>
	</div>
	<div class="row">
		<div class="col-md-8 col-offset-2 col-xs-8 col-xs-offset-2">
			<h2 class="text-center">
				Wins
			</h2>
		</div>
	</div>
	<div class="row">
		<div class="col-md-8 col-offset-2 col-xs-8 col-xs-offset-2">
			<h4 class="text-center">
				<%= @user.wins %>
			</h4>
		</div>
	</div>
	<div class="row">
		<div class="col-md-8 col-offset-2 col-xs-8 col-xs-offset-2">
			<h2 class="text-center">
				Loses
			</h2>
		</div>
	</div>
	<div class="row">
		<div class="col-md-8 col-offset-2 col-xs-8 col-xs-offset-2">
			<h4 class="text-center">
			 <%= @user.losses %>
			</h4>
		</div>
	</div>
	<div class="row">
		<div class="col-md-8 col-offset-2 col-xs-8 col-xs-offset-2">
			<h2 class="text-center">
				Total Games
			</h2>
		</div>
	</div>
	<div class="row">
		<div class="col-md-8 col-offset-2 col-xs-8 col-xs-offset-2">
			<h4 class="text-center">
				<%= @user.total_game %>
			</h4>
		</div>
	</div>
	<div class="row">
		<div class="col-md-8 col-offset-2 col-xs-8 col-xs-offset-2">
			<%= link_to "Edit Profile", edit_user_path, class: "btn btn-danger" %>
		</div>
	</div>
	<% if authorized? %>
	<div class="row">
		<div class="col-md-8 col-offset-2 col-xs-8 col-xs-offset-2">
			<%= link_to "Destory Profile", users_path, method: :delete, data: {confirm: "Are You Sure?"}, class: "btn btn-danger" %>
		</div>
	</div>
	<% end %>
</div>

app/views/welcome/index.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col-md-8 col-md-offset-2 col-xs-8 col-xs-offset-2">
			<h1 class="text-center">
				Who Lives?
			</h1>
		</div>
	</div>
	<% if login? %>
		<div class="row">
			<div class="col-md-8 col-md-offset-2 col-xs-8 col-xs-offset-2 text-center">
				<%= link_to "Start A New Game", new_game_path, class: "btn btn-primary" %>
			</div>
		</div>
	<% else %>
		<div class="row">
			<div class="col-md-8 col-md-offset-2 col-xs-8 col-xs-offset-2">
				<h2 class="text-center">
					Fresh Meat?
				</h2>
			</div>
		</div>
		<div clas="row">
			<div class="col-md-8 col-md-offset-2 col-xs-8 col-xs-offset-2 text-center">
				<%= link_to "Sign Up Here", sign_up_path, class: "btn btn-danger" %>
			</div>
		</div>
		<div class="row">
			<div class="col-md-8 col-md-offset-2 col-xs-8 col-xs-offset-2">
				<h2 class="text-center">
					Back To Serve Your Sentence?
				</h2>
			</div>
		</div>
		<div class="row">
			<div class="col-md-8 col-xs-offset-2 col-xs-8 col-xs-offset-2 text-center">
				<%= link_to "Log In Here", log_in_path, class: "btn btn-danger", id:"login" %>
			</div>
		</div>
		<div class="row">
			<div class="col-md-8 col-xs-offset-2 col-xs-8 col-xs-offset-2 text-center">
				<%= link_to "Log In With Facebook", "/auth/facebook", class: "btn btn-primary" %>
			</div>
		</div>
	<% end %>
</div>